create table items
(
    id                    integer not null
        constraint items_pkey
            primary key,
    name                  varchar not null,
    cost                  integer not null,
    secret_shop           integer not null,
    side_shop             integer not null,
    recipe                integer not null,
    localized_name        varchar not null,
    localized_description varchar
);

alter table items
    owner to postgres;

INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (17, 'item_belt_of_strength', 450, 0, 0, 0, 'Belt of Strength', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (18, 'item_boots_of_elves', 450, 0, 0, 0, 'Band of Elvenskin', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (19, 'item_robe', 450, 0, 0, 0, 'Robe of the Magi', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (20, 'item_circlet', 155, 0, 0, 0, 'Circlet', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (261, 'item_crown', 450, 0, 0, 0, 'Crown', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (21, 'item_ogre_axe', 1000, 0, 0, 0, 'Ogre Axe', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (22, 'item_blade_of_alacrity', 1000, 0, 0, 0, 'Blade of Alacrity', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (23, 'item_staff_of_wizardry', 1000, 0, 0, 0, 'Staff of Wizardry', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (51, 'item_demon_edge', 2200, 1, 0, 0, 'Demon Edge', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (52, 'item_eagle', 2800, 1, 0, 0, 'Eaglesong', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (829, 'item_force_field', 0, 0, 0, 0, 'Arcanist''s Armor', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (833, 'item_tree_processor', 0, 0, 0, 0, 'Tree Processor', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (834, 'item_black_powder_bag', 0, 0, 0, 0, 'Blast Rig', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (849, 'item_mechanical_arm', 0, 0, 0, 0, 'Mechanical Arm', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (824, 'item_assassins_dagger', 0, 0, 0, 0, 'Assassin''s Dagger', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (825, 'item_ascetic_cap', 0, 0, 0, 0, 'Ascetic''s Cap', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (826, 'item_sample_picker', 0, 0, 0, 0, 'Assassin''s Contract', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (827, 'item_icarus_wings', 0, 0, 0, 0, 'Icarus Wings', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (828, 'item_misericorde', 0, 0, 0, 0, 'Brigand''s Blade', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (836, 'item_light_robes', 0, 0, 0, 0, 'Light Robes', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (837, 'item_heavy_blade', 0, 0, 0, 0, 'Witchbane', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (838, 'item_unstable_wand', 0, 0, 0, 0, 'Pig Pole', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (839, 'item_fortitude_ring', 0, 0, 0, 0, 'Ring of Fortitude', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (840, 'item_pogo_stick', 0, 0, 0, 0, 'Tumbler''s Toy', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (835, 'item_paintball', 0, 0, 0, 0, 'Fae Grenade', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (24, 'item_ultimate_orb', 2050, 1, 0, 0, 'Ultimate Orb', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (25, 'item_gloves', 450, 0, 0, 0, 'Gloves of Haste', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (485, 'item_blitz_knuckles', 1000, 0, 0, 0, 'Blitz Knuckles', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (26, 'item_lifesteal', 900, 0, 0, 0, 'Morbid Mask', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (473, 'item_voodoo_mask', 700, 0, 0, 0, 'Voodoo Mask', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (27, 'item_ring_of_regen', 175, 0, 0, 0, 'Ring of Regen', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (279, 'item_ring_of_tarrasque', 650, 0, 0, 0, 'Ring of Tarrasque', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (36, 'item_magic_wand', 450, 0, 0, 0, 'Magic Wand', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (38, 'item_clarity', 50, 0, 0, 0, 'Clarity', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (53, 'item_reaver', 2800, 1, 0, 0, 'Reaver', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (54, 'item_relic', 3800, 1, 0, 0, 'Sacred Relic', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (55, 'item_hyperstone', 2000, 1, 0, 0, 'Hyperstone', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (56, 'item_ring_of_health', 825, 1, 0, 0, 'Ring of Health', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (57, 'item_void_stone', 825, 1, 0, 0, 'Void Stone', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (58, 'item_mystic_staff', 2800, 1, 0, 0, 'Mystic Staff', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (59, 'item_energy_booster', 800, 1, 0, 0, 'Energy Booster', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (60, 'item_point_booster', 1200, 1, 0, 0, 'Point Booster', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (61, 'item_vitality_booster', 1000, 1, 0, 0, 'Vitality Booster', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (593, 'item_fluffy_hat', 250, 0, 0, 0, 'Fluffy Hat', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (62, 'item_recipe_power_treads', 0, 0, 0, 1, 'Recipe: Power Treads', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (63, 'item_power_treads', 1400, 0, 0, 0, 'Power Treads', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (653, 'item_recipe_grandmasters_glaive', 0, 0, 0, 1, 'Recipe: Grandmaster''s Glaive', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (655, 'item_grandmasters_glaive', 5000, 0, 0, 0, 'Grandmaster''s Glaive', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (64, 'item_recipe_hand_of_midas', 1750, 0, 0, 1, 'Recipe: Hand of Midas', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (610, 'item_wind_waker', 6825, 0, 0, 0, 'Wind Waker', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (233, 'item_recipe_aether_lens', 650, 0, 0, 1, 'Recipe: Aether Lens', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (232, 'item_aether_lens', 2275, 0, 0, 0, 'Aether Lens', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (727, 'item_ultimate_scepter_roshan', 5800, 0, 0, 0, 'Aghanim''s Blessing - Roshan', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (216, 'item_enchanted_mango', 65, 0, 0, 0, 'Enchanted Mango', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (39, 'item_flask', 110, 0, 0, 0, 'Healing Salve', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (40, 'item_dust', 80, 0, 0, 0, 'Dust of Appearance', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (41, 'item_bottle', 675, 0, 0, 0, 'Bottle', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (42, 'item_ward_observer', 0, 0, 0, 0, 'Observer Ward', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (43, 'item_ward_sentry', 50, 0, 0, 0, 'Sentry Ward', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (217, 'item_recipe_ward_dispenser', 0, 0, 0, 1, 'Recipe: Observer and Sentry Wards', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (241, 'item_tango_single', 30, 0, 0, 0, 'Tango (Shared)', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (45, 'item_courier', 50, 0, 0, 0, 'Animal Courier', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (286, 'item_flying_courier', 100, 0, 0, 0, 'Flying Courier', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (46, 'item_tpscroll', 100, 0, 0, 0, 'Town Portal Scroll', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (220, 'item_travel_boots_2', 4500, 0, 0, 0, 'Boots of Travel 2', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (196, 'item_spirit_vessel', 2825, 0, 0, 0, 'Spirit Vessel', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (49, 'item_recipe_phase_boots', 0, 0, 0, 1, 'Recipe: Phase Boots', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (50, 'item_phase_boots', 1500, 0, 0, 0, 'Phase Boots', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (101, 'item_recipe_force_staff', 950, 0, 0, 1, 'Recipe: Force Staff', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (102, 'item_force_staff', 2200, 0, 0, 0, 'Force Staff', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (262, 'item_recipe_hurricane_pike', 450, 0, 0, 1, 'Recipe: Hurricane Pike', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (263, 'item_hurricane_pike', 4550, 0, 0, 0, 'Hurricane Pike', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (103, 'item_recipe_dagon', 1250, 0, 0, 1, 'Recipe: Dagon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (197, 'item_recipe_dagon_2', 0, 0, 0, 1, 'Recipe: Dagon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (198, 'item_recipe_dagon_3', 0, 0, 0, 1, 'Recipe: Dagon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (199, 'item_recipe_dagon_4', 0, 0, 0, 1, 'Recipe: Dagon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (200, 'item_recipe_dagon_5', 0, 0, 0, 1, 'Recipe: Dagon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (201, 'item_dagon_2', 3950, 0, 0, 0, 'Dagon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (202, 'item_dagon_3', 5200, 0, 0, 0, 'Dagon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (203, 'item_dagon_4', 6450, 0, 0, 0, 'Dagon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (204, 'item_dagon_5', 7700, 0, 0, 0, 'Dagon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (105, 'item_recipe_necronomicon', 1250, 0, 0, 1, 'Recipe: Necronomicon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (191, 'item_recipe_necronomicon_2', 0, 0, 0, 1, 'Recipe: Necronomicon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (192, 'item_recipe_necronomicon_3', 0, 0, 0, 1, 'Recipe: Necronomicon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (106, 'item_necronomicon', 2050, 0, 0, 0, 'Necronomicon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (193, 'item_necronomicon_2', 3300, 0, 0, 0, 'Necronomicon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (194, 'item_necronomicon_3', 4550, 0, 0, 0, 'Necronomicon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (107, 'item_recipe_ultimate_scepter', 0, 0, 0, 1, 'Recipe: Aghanim''s Scepter', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (108, 'item_ultimate_scepter', 4200, 0, 0, 0, 'Aghanim''s Scepter', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (270, 'item_recipe_ultimate_scepter_2', 1600, 0, 0, 1, 'Recipe: Aghanim''s Blessing', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (271, 'item_ultimate_scepter_2', 5800, 0, 0, 0, 'Aghanim''s Blessing', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (609, 'item_aghanims_shard', 1400, 0, 0, 0, 'Aghanim''s Shard', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (110, 'item_refresher', 5000, 0, 0, 0, 'Refresher Orb', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (111, 'item_recipe_assault', 1300, 0, 0, 1, 'Recipe: Assault Cuirass', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (113, 'item_recipe_heart', 1300, 0, 0, 1, 'Recipe: Heart of Tarrasque', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (114, 'item_heart', 5100, 0, 0, 0, 'Heart of Tarrasque', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (115, 'item_recipe_black_king_bar', 1450, 0, 0, 1, 'Recipe: Black King Bar', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (117, 'item_aegis', 0, 0, 0, 0, 'Aegis of the Immortal', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (118, 'item_recipe_shivas_guard', 650, 0, 0, 1, 'Recipe: Shiva''s Guard', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (120, 'item_recipe_bloodstone', 0, 0, 0, 1, 'Recipe: Bloodstone', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (121, 'item_bloodstone', 5750, 0, 0, 0, 'Bloodstone', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (122, 'item_recipe_sphere', 900, 0, 0, 1, 'Recipe: Linken''s Sphere', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (221, 'item_recipe_lotus_orb', 0, 0, 0, 1, 'Recipe: Lotus Orb', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (222, 'item_recipe_meteor_hammer', 250, 0, 0, 1, 'Recipe: Meteor Hammer', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (224, 'item_recipe_nullifier', 0, 0, 0, 1, 'Recipe: Nullifier', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (255, 'item_recipe_aeon_disk', 1200, 0, 0, 1, 'Recipe: Aeon Disk', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (258, 'item_recipe_kaya', 600, 0, 0, 1, 'Recipe: Kaya', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (369, 'item_trident', 0, 0, 0, 0, 'Trident', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (725, 'item_aghanims_shard_roshan', 1400, 0, 0, 0, 'Aghanim''s Shard - Roshan', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (109, 'item_recipe_refresher', 1700, 0, 0, 1, 'Recipe: Refresher Orb', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (112, 'item_assault', 5125, 0, 0, 0, 'Assault Cuirass', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (266, 'item_recipe_spirit_vessel', 1000, 0, 0, 1, 'Recipe: Spirit Vessel', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (267, 'item_spirit_vessel', 2840, 0, 0, 0, 'Spirit Vessel', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (124, 'item_recipe_vanguard', 0, 0, 0, 1, 'Recipe: Vanguard', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (150, 'item_recipe_armlet', 650, 0, 0, 1, 'Recipe: Armlet of Mordiggian', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (151, 'item_armlet', 2475, 0, 0, 0, 'Armlet of Mordiggian', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (161, 'item_recipe_sange', 600, 0, 0, 1, 'Recipe: Sange', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (163, 'item_recipe_helm_of_the_dominator', 975, 0, 0, 1, 'Recipe: Helm of the Dominator', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (164, 'item_helm_of_the_dominator', 2350, 0, 0, 0, 'Helm of the Dominator', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (633, 'item_recipe_helm_of_the_overlord', 1250, 0, 0, 1, 'Recipe: Helm of the Overlord', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (635, 'item_helm_of_the_overlord', 6300, 0, 0, 0, 'Helm of the Overlord', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (165, 'item_recipe_maelstrom', 0, 0, 0, 1, 'Recipe: Maelstrom', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (214, 'item_tranquil_boots', 925, 0, 0, 0, 'Tranquil Boots', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (215, 'item_shadow_amulet', 1000, 0, 0, 0, 'Shadow Amulet', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (253, 'item_recipe_glimmer_cape', 450, 0, 0, 1, 'Recipe: Glimmer Cape', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (254, 'item_glimmer_cape', 1950, 0, 0, 0, 'Glimmer Cape', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1021, 'item_river_painter', 0, 0, 0, 0, 'River Vial: Chrome', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1022, 'item_river_painter2', 0, 0, 0, 0, 'River Vial: Dry', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1023, 'item_river_painter3', 0, 0, 0, 0, 'River Vial: Slime', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1024, 'item_river_painter4', 0, 0, 0, 0, 'River Vial: Oil', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1025, 'item_river_painter5', 0, 0, 0, 0, 'River Vial: Electrified', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1026, 'item_river_painter6', 0, 0, 0, 0, 'River Vial: Potion', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1027, 'item_river_painter7', 0, 0, 0, 0, 'River Vial: Blood', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1028, 'item_mutation_tombstone', 0, 0, 0, 0, 'Tombstone', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (299, 'item_greater_faerie_fire', 0, 0, 0, 0, 'Greater Faerie Fire', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (300, 'item_timeless_relic', 0, 0, 0, 0, 'Timeless Relic', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1031, 'item_tpscroll_2', 50, 0, 1, 0, 'Town Portal Scroll', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (301, 'item_mirror_shield', 0, 0, 0, 0, 'Mirror Shield', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (303, 'item_recipe_ironwood_tree', 1, 0, 0, 1, 'Recipe: Ironwood Tree', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (304, 'item_ironwood_tree', 151, 0, 0, 0, 'Ironwood Tree', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (328, 'item_mango_tree', 0, 0, 0, 0, 'Mango Tree', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (305, 'item_royal_jelly', 0, 0, 0, 0, 'Royal Jelly', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (306, 'item_pupils_gift', 0, 0, 0, 0, 'Pupil''s Gift', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (307, 'item_tome_of_aghanim', 0, 0, 0, 0, 'Tome of Aghanim', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (308, 'item_repair_kit', 0, 0, 0, 0, 'Repair Kit', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (309, 'item_mind_breaker', 0, 0, 0, 0, 'Mind Breaker', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (310, 'item_third_eye', 0, 0, 0, 0, 'Third Eye', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (311, 'item_spell_prism', 0, 0, 0, 0, 'Spell Prism', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (325, 'item_princes_knife', 0, 0, 0, 0, 'Prince''s Knife', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (330, 'item_witless_shako', 0, 0, 0, 0, 'Witless Shako', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (276, 'item_combo_breaker', 0, 0, 0, 0, 'DOTA_Tooltip_Ability_item_combo_breaker', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (260, 'item_refresher_shard', 1000, 0, 0, 0, 'Refresher Shard', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (243, 'item_recipe_crimson_guard', 950, 0, 0, 1, 'Recipe: Crimson Guard', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (273, 'item_kaya_and_sange', 4100, 0, 0, 0, 'Kaya and Sange', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (274, 'item_recipe_yasha_and_kaya', 0, 0, 0, 1, 'Recipe: Yasha and Kaya', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (277, 'item_yasha_and_kaya', 4100, 0, 0, 0, 'Yasha and Kaya', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (155, 'item_recipe_satanic', 0, 0, 0, 1, 'Recipe: Satanic', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (156, 'item_satanic', 5050, 0, 0, 0, 'Satanic', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (157, 'item_recipe_mjollnir', 900, 0, 0, 1, 'Recipe: Mjollnir', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (159, 'item_recipe_skadi', 0, 0, 0, 1, 'Recipe: Eye of Skadi', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (160, 'item_skadi', 5300, 0, 0, 0, 'Eye of Skadi', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (242, 'item_crimson_guard', 3700, 0, 0, 0, 'Crimson Guard', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (126, 'item_recipe_blade_mail', 575, 0, 0, 1, 'Recipe: Blade Mail', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (128, 'item_recipe_soul_booster', 0, 0, 0, 1, 'Recipe: Soul Booster', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (140, 'item_recipe_greater_crit', 1000, 0, 0, 1, 'Recipe: Daedalus', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (141, 'item_greater_crit', 5150, 0, 0, 0, 'Daedalus', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (144, 'item_recipe_bfury', 0, 0, 0, 1, 'Recipe: Battle Fury', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (146, 'item_recipe_manta', 500, 0, 0, 1, 'Recipe: Manta Style', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (147, 'item_manta', 4600, 0, 0, 0, 'Manta Style', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (148, 'item_recipe_lesser_crit', 500, 0, 0, 1, 'Recipe: Crystalys', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (149, 'item_lesser_crit', 1950, 0, 0, 0, 'Crystalys', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (234, 'item_recipe_dragon_lance', 0, 0, 0, 1, 'Recipe: Dragon Lance', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (236, 'item_dragon_lance', 1900, 0, 0, 0, 'Dragon Lance', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (183, 'item_recipe_invis_sword', 0, 0, 0, 1, 'Recipe: Shadow Blade', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (142, 'item_recipe_basher', 900, 0, 0, 1, 'Recipe: Skull Basher', '');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (226, 'item_lotus_orb', 3850, 0, 0, 0, 'Lotus Orb', 'Applies a shield to the target unit for <strong>6</strong> seconds which re-casts most targeted spells back to their caster.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (248, 'item_recipe_silver_edge', 500, 0, 0, 1, 'Recipe: Silver Edge', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (153, 'item_recipe_sange_and_yasha', 0, 0, 0, 1, 'Recipe: Sange and Yasha', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (154, 'item_sange_and_yasha', 4100, 0, 0, 0, 'Sange and Yasha', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (272, 'item_recipe_kaya_and_sange', 0, 0, 0, 1, 'Recipe: Kaya and Sange', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (597, 'item_recipe_mage_slayer', 400, 0, 0, 1, 'Recipe: Mage Slayer', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (184, 'item_recipe_ancient_janggo', 550, 0, 0, 1, 'Recipe: Drum of Endurance', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (188, 'item_smoke_of_deceit', 50, 0, 0, 0, 'Smoke of Deceit', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (190, 'item_veil_of_discord', 1525, 0, 0, 0, 'Veil of Discord', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (230, 'item_recipe_guardian_greaves', 1600, 0, 0, 1, 'Recipe: Guardian Greaves', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (231, 'item_guardian_greaves', 5200, 0, 0, 0, 'Guardian Greaves', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (205, 'item_recipe_rod_of_atos', 850, 0, 0, 1, 'Recipe: Rod of Atos', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (238, 'item_recipe_iron_talon', 1, 0, 0, 1, 'Recipe: Iron Talon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (239, 'item_iron_talon', 301, 0, 0, 0, 'Iron Talon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (207, 'item_recipe_abyssal_blade', 1550, 0, 0, 1, 'Recipe: Abyssal Blade', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (209, 'item_recipe_heavens_halberd', 200, 0, 0, 1, 'Recipe: Heaven''s Halberd', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (329, 'item_recipe_vambrace', 0, 0, 0, 1, 'Recipe: Vambrace', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (331, 'item_vambrace', 0, 0, 0, 0, 'Vambrace', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (312, 'item_horizon', 0, 0, 0, 0, 'Horizon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (313, 'item_fusion_rune', 0, 0, 0, 0, 'Fusion Rune', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (354, 'item_ocean_heart', 0, 0, 0, 0, 'Ocean Heart', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (355, 'item_broom_handle', 0, 0, 0, 0, 'Broom Handle', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (356, 'item_trusty_shovel', 0, 0, 0, 0, 'Trusty Shovel', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (357, 'item_nether_shawl', 0, 0, 0, 0, 'Nether Shawl', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (358, 'item_dragon_scale', 0, 0, 0, 0, 'Dragon Scale', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (359, 'item_essence_ring', 0, 0, 0, 0, 'Essence Ring', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (360, 'item_clumsy_net', 0, 0, 0, 0, 'Clumsy Net', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (361, 'item_enchanted_quiver', 0, 0, 0, 0, 'Enchanted Quiver', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (362, 'item_ninja_gear', 0, 0, 0, 0, 'Ninja Gear', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (363, 'item_illusionsts_cape', 0, 0, 0, 0, 'Illusionist''s Cape', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (364, 'item_havoc_hammer', 0, 0, 0, 0, 'Havoc Hammer', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (365, 'item_panic_button', 0, 0, 0, 0, 'Magic Lamp', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (367, 'item_ballista', 0, 0, 0, 0, 'Ballista', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (368, 'item_woodland_striders', 0, 0, 0, 0, 'Woodland Striders', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (275, 'item_recipe_trident', 1, 0, 0, 1, 'Recipe: Trident', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (370, 'item_demonicon', 0, 0, 0, 0, 'Book of the Dead', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (317, 'item_recipe_fallen_sky', 1, 0, 0, 1, 'Recipe: Fallen Sky', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (371, 'item_fallen_sky', 4751, 0, 0, 0, 'Fallen Sky', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (372, 'item_pirate_hat', 0, 0, 0, 0, 'Pirate Hat', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (373, 'item_dimensional_doorway', 0, 0, 0, 0, 'Dimensional Doorway', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (374, 'item_ex_machina', 0, 0, 0, 0, 'Ex Machina', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (375, 'item_faded_broach', 0, 0, 0, 0, 'Faded Broach', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (376, 'item_paladin_sword', 0, 0, 0, 0, 'Paladin Sword', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (377, 'item_minotaur_horn', 0, 0, 0, 0, 'Minotaur Horn', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (378, 'item_orb_of_destruction', 0, 0, 0, 0, 'Orb of Destruction', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (379, 'item_the_leveller', 0, 0, 0, 0, 'The Leveller', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (349, 'item_arcane_ring', 0, 0, 0, 0, 'Arcane Ring', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (381, 'item_titan_sliver', 0, 0, 0, 0, 'Titan Sliver', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (173, 'item_recipe_diffusal_blade', 700, 0, 0, 1, 'Recipe: Diffusal Blade', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (175, 'item_recipe_ethereal_blade', 0, 0, 0, 1, 'Recipe: Ethereal Blade', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (177, 'item_recipe_soul_ring', 225, 0, 0, 1, 'Recipe: Soul Ring', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (178, 'item_soul_ring', 680, 0, 0, 0, 'Soul Ring', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (179, 'item_recipe_arcane_boots', 0, 0, 0, 1, 'Recipe: Arcane Boots', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (180, 'item_arcane_boots', 1300, 0, 0, 0, 'Arcane Boots', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (228, 'item_recipe_octarine_core', 0, 0, 0, 1, 'Recipe: Octarine Core', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (235, 'item_octarine_core', 5275, 0, 0, 0, 'Octarine Core', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (181, 'item_orb_of_venom', 275, 0, 0, 0, 'Orb of Venom', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (240, 'item_blight_stone', 300, 0, 0, 0, 'Blight Stone', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (640, 'item_recipe_orb_of_corrosion', 100, 0, 0, 1, 'Recipe: Orb of Corrosion', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (569, 'item_orb_of_corrosion', 925, 0, 0, 0, 'Orb of Corrosion', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (599, 'item_recipe_falcon_blade', 225, 0, 0, 1, 'Recipe: Falcon Blade', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (596, 'item_falcon_blade', 1100, 0, 0, 0, 'Falcon Blade', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (211, 'item_recipe_ring_of_aquila', 0, 0, 0, 1, 'Recipe: Ring of Aquila', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (212, 'item_ring_of_aquila', 0, 0, 0, 0, 'Ring of Aquila', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (213, 'item_recipe_tranquil_boots', 0, 0, 0, 1, 'Recipe: Tranquil Boots', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (334, 'item_imp_claw', 0, 0, 0, 0, 'Imp Claw', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (335, 'item_flicker', 0, 0, 0, 0, 'Flicker', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (336, 'item_spy_gadget', 0, 0, 0, 0, 'Telescope', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (326, 'item_spider_legs', 0, 0, 0, 0, 'Spider Legs', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (327, 'item_helm_of_the_undying', 0, 0, 0, 0, 'Helm of the Undying', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (565, 'item_chipped_vest', 0, 0, 0, 0, 'Chipped Vest', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (566, 'item_wizard_glass', 0, 0, 0, 0, 'Wizard Glass', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (570, 'item_gloves_of_travel', 0, 0, 0, 0, 'Gloves of Travel', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (573, 'item_elven_tunic', 0, 0, 0, 0, 'Elven Tunic', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (574, 'item_cloak_of_flames', 0, 0, 0, 0, 'Cloak of Flames', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (575, 'item_venom_gland', 0, 0, 0, 0, 'Venom Gland', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (571, 'item_trickster_cloak', 0, 0, 0, 0, 'Trickster Cloak', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (576, 'item_gladiator_helm', 0, 0, 0, 0, 'Helm of the Gladiator', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1565, 'item_recipe_gungir', 700, 0, 0, 1, 'Recipe: Gleipnir', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (167, 'item_recipe_desolator', 0, 0, 0, 1, 'Recipe: Desolator', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (169, 'item_recipe_yasha', 600, 0, 0, 1, 'Recipe: Yasha', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (171, 'item_recipe_mask_of_madness', 0, 0, 0, 1, 'Recipe: Mask of Madness', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (598, 'item_mage_slayer', 2400, 0, 0, 0, 'Mage Slayer', 'Places a debuff when you attack enemies');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (172, 'item_mask_of_madness', 1775, 0, 0, 0, 'Mask of Madness', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1002, 'item_mystery_arrow', 0, 0, 0, 0, 'DOTA_Tooltip_Ability_item_mystery_arrow', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1005, 'item_mystery_vacuum', 0, 0, 0, 0, 'DOTA_Tooltip_Ability_item_mystery_vacuum', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1008, 'item_greevil_whistle_toggle', 0, 0, 0, 0, 'Greevil Whistle', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1011, 'item_winter_skates', 0, 0, 0, 0, 'Speed Skates', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1014, 'item_winter_coco', 0, 0, 0, 0, 'Cocoa with Marshmallows', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1017, 'item_winter_mushroom', 0, 0, 0, 0, 'Snow Mushroom', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1020, 'item_winter_greevil_chewy', 0, 0, 0, 0, 'Greevil Blink Bone', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1000, 'item_halloween_candy_corn', 0, 0, 0, 0, 'Greevil Taffy', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1003, 'item_mystery_missile', 0, 0, 0, 0, 'DOTA_Tooltip_Ability_item_mystery_missile', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1006, 'item_halloween_rapier', 6200, 0, 0, 0, 'DOTA_Tooltip_Ability_item_halloween_rapier', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1009, 'item_present', 0, 0, 0, 0, 'A Gift!', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1012, 'item_winter_cake', 0, 0, 0, 0, 'Fruit-bit Cake', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1015, 'item_winter_ham', 0, 0, 0, 0, 'Clove Studded Ham', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1018, 'item_winter_greevil_treat', 0, 0, 0, 0, 'Greevil Treat', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1001, 'item_mystery_hook', 0, 0, 0, 0, 'DOTA_Tooltip_Ability_item_mystery_hook', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1004, 'item_mystery_toss', 0, 0, 0, 0, 'DOTA_Tooltip_Ability_item_mystery_toss', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1007, 'item_greevil_whistle', 0, 0, 0, 0, 'Greevil Whistle', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1010, 'item_winter_stocking', 0, 0, 0, 0, 'Xmas Stocking', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1013, 'item_winter_cookie', 0, 0, 0, 0, 'Wizard Cookie', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1016, 'item_winter_kringle', 0, 0, 0, 0, 'Kringle', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1019, 'item_winter_greevil_garbage', 0, 0, 0, 0, 'Greevil Chow', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (264, 'item_banana', 0, 0, 0, 0, 'Banana', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (104, 'item_dagon', 2700, 0, 0, 0, 'Dagon', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (125, 'item_vanguard', 1825, 0, 0, 0, 'Vanguard', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (9, 'item_platemail', 1400, 1, 0, 0, 'Platemail', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (257, 'item_tome_of_knowledge', 75, 0, 0, 0, 'Tome of Knowledge', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (189, 'item_recipe_veil_of_discord', 650, 0, 0, 1, 'Recipe: Veil of Discord', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (678, 'item_giants_ring', 0, 0, 0, 0, 'Giant''s Ring', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (679, 'item_vengeances_shadow', 0, 0, 0, 0, 'Shadow of Vengeance', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (585, 'item_stormcrafter', 0, 0, 0, 0, 'Stormcrafter', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (588, 'item_overflowing_elixir', 0, 0, 0, 0, 'Overflowing Elixir', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (589, 'item_mysterious_hat', 0, 0, 0, 0, 'Fairy''s Trinket', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (10, 'item_quarterstaff', 875, 0, 0, 0, 'Quarterstaff', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (11, 'item_quelling_blade', 130, 0, 0, 0, 'Quelling Blade', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (237, 'item_faerie_fire', 70, 0, 0, 0, 'Faerie Fire', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (265, 'item_infused_raindrop', 225, 0, 0, 0, 'Infused Raindrops', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (244, 'item_wind_lace', 250, 0, 0, 0, 'Wind Lace', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (12, 'item_ring_of_protection', 175, 0, 0, 0, 'Ring of Protection', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (182, 'item_stout_shield', 100, 0, 0, 0, 'Stout Shield', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (246, 'item_recipe_moon_shard', 0, 0, 0, 1, 'Recipe: Moon Shard', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (247, 'item_moon_shard', 4000, 0, 0, 0, 'Moon Shard', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (13, 'item_gauntlets', 140, 0, 0, 0, 'Gauntlets of Strength', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (14, 'item_slippers', 140, 0, 0, 0, 'Slippers of Agility', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (15, 'item_mantle', 140, 0, 0, 0, 'Mantle of Intelligence', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (16, 'item_branches', 50, 0, 0, 0, 'Iron Branch', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (65, 'item_hand_of_midas', 2200, 0, 0, 0, 'Hand of Midas', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (66, 'item_recipe_oblivion_staff', 0, 0, 0, 1, 'Recipe: Oblivion Staff', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (67, 'item_oblivion_staff', 1500, 0, 0, 0, 'Oblivion Staff', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (533, 'item_recipe_witch_blade', 600, 0, 0, 1, 'Recipe: Witch Blade', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (534, 'item_witch_blade', 2600, 0, 0, 0, 'Witch Blade', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (68, 'item_recipe_pers', 0, 0, 0, 1, 'Recipe: Perseverance', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (69, 'item_pers', 1650, 0, 0, 0, 'Perseverance', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (70, 'item_recipe_poor_mans_shield', 0, 0, 0, 1, 'Recipe: Poor Man''s Shield', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (71, 'item_poor_mans_shield', 0, 0, 0, 0, 'Poor Man''s Shield', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (731, 'item_satchel', 0, 0, 0, 0, 'Satchel', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (686, 'item_quicksilver_amulet', 0, 0, 0, 0, 'Quicksilver Amulet', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (677, 'item_book_of_shadows', 0, 0, 0, 0, 'Book of Shadows', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (48, 'item_travel_boots', 2500, 0, 0, 0, 'Boots of Travel', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (72, 'item_recipe_bracer', 210, 0, 0, 1, 'Recipe: Bracer', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (73, 'item_bracer', 505, 0, 0, 0, 'Bracer', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (74, 'item_recipe_wraith_band', 210, 0, 0, 1, 'Recipe: Wraith Band', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (75, 'item_wraith_band', 505, 0, 0, 0, 'Wraith Band', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (259, 'item_kaya', 2050, 0, 0, 0, 'Kaya', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (76, 'item_recipe_null_talisman', 210, 0, 0, 1, 'Recipe: Null Talisman', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (77, 'item_null_talisman', 505, 0, 0, 0, 'Null Talisman', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (78, 'item_recipe_mekansm', 900, 0, 0, 1, 'Recipe: Mekansm', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (79, 'item_mekansm', 1875, 0, 0, 0, 'Mekansm', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (80, 'item_recipe_vladmir', 500, 0, 0, 1, 'Recipe: Vladmir''s Offering', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (81, 'item_vladmir', 2700, 0, 0, 0, 'Vladmir''s Offering', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (85, 'item_recipe_buckler', 250, 0, 0, 1, 'Recipe: Buckler', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (86, 'item_buckler', 425, 0, 0, 0, 'Buckler', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (87, 'item_recipe_ring_of_basilius', 250, 0, 0, 1, 'Recipe: Ring of Basilius', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (88, 'item_ring_of_basilius', 425, 0, 0, 0, 'Ring of Basilius', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (91, 'item_recipe_urn_of_shadows', 335, 0, 0, 1, 'Recipe: Urn of Shadows', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (92, 'item_urn_of_shadows', 840, 0, 0, 0, 'Urn of Shadows', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (93, 'item_recipe_headdress', 250, 0, 0, 1, 'Recipe: Headdress', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (95, 'item_recipe_sheepstick', 0, 0, 0, 1, 'Recipe: Scythe of Vyse', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (97, 'item_recipe_orchid', 475, 0, 0, 1, 'Recipe: Orchid Malevolence', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (245, 'item_recipe_bloodthorn', 800, 0, 0, 1, 'Recipe: Bloodthorn', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (251, 'item_recipe_echo_sabre', 0, 0, 0, 1, 'Recipe: Echo Sabre', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (252, 'item_echo_sabre', 2500, 0, 0, 0, 'Echo Sabre', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (99, 'item_recipe_cyclone', 650, 0, 0, 1, 'Recipe: Eul''s Scepter of Divinity', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (100, 'item_cyclone', 2725, 0, 0, 0, 'Eul''s Scepter of Divinity', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (612, 'item_recipe_wind_waker', 1300, 0, 0, 1, 'Recipe: Wind Waker', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (47, 'item_recipe_travel_boots', 2000, 0, 0, 1, 'Recipe: Boots of Travel', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (219, 'item_recipe_travel_boots_2', 0, 0, 0, 1, 'Recipe: Boots of Travel 2', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (90, 'item_pipe', 3475, 0, 0, 0, 'Pipe of Insight', 'Gives a shield that blocks <strong>400</strong> magic damage to all nearby allies. Lasts <strong>12</strong> seconds.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (129, 'item_soul_booster', 3000, 0, 0, 0, 'Soul Booster', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (130, 'item_recipe_hood_of_defiance', 0, 0, 0, 1, 'Recipe: Hood of Defiance', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (691, 'item_recipe_eternal_shroud', 1100, 0, 0, 1, 'Recipe: Eternal Shroud', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (132, 'item_recipe_rapier', 0, 0, 0, 1, 'Recipe: Divine Rapier', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (133, 'item_rapier', 6000, 0, 0, 0, 'Divine Rapier', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (134, 'item_recipe_monkey_king_bar', 675, 0, 0, 1, 'Recipe: Monkey King Bar', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (136, 'item_recipe_radiance', 1350, 0, 0, 1, 'Recipe: Radiance', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (138, 'item_recipe_butterfly', 0, 0, 0, 1, 'Recipe: Butterfly', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (139, 'item_butterfly', 4975, 0, 0, 0, 'Butterfly', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (170, 'item_yasha', 2050, 0, 0, 0, 'Yasha', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (94, 'item_headdress', 425, 0, 0, 0, 'Headdress', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (185, 'item_ancient_janggo', 1700, 0, 0, 0, 'Drum of Endurance', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (186, 'item_recipe_medallion_of_courage', 0, 0, 0, 1, 'Recipe: Medallion of Courage', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (187, 'item_medallion_of_courage', 1025, 0, 0, 0, 'Medallion of Courage', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (227, 'item_recipe_solar_crest', 900, 0, 0, 1, 'Recipe: Solar Crest', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (577, 'item_possessed_mask', 0, 0, 0, 0, 'Possessed Mask', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (578, 'item_ancient_perseverance', 0, 0, 0, 0, 'Ancient Perseverance', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (637, 'item_star_mace', 0, 0, 0, 0, 'Star Mace', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (638, 'item_penta_edged_sword', 0, 0, 0, 0, 'Penta-Edged Sword', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (582, 'item_oakheart', 0, 0, 0, 0, 'Oakheart', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (674, 'item_warhammer', 0, 0, 0, 0, 'Warhammer', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (680, 'item_bullwhip', 0, 0, 0, 0, 'Bullwhip', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (675, 'item_psychic_headband', 0, 0, 0, 0, 'Psychic Headband', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (676, 'item_ceremonial_robe', 0, 0, 0, 0, 'Ceremonial Robe', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (268, 'item_recipe_holy_locket', 475, 0, 0, 1, 'Recipe: Holy Locket', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (269, 'item_holy_locket', 2400, 0, 0, 0, 'Holy Locket', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (89, 'item_recipe_pipe', 1550, 0, 0, 1, 'Recipe: Pipe of Insight', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1029, 'item_super_blink', 0, 0, 0, 0, 'Super Blink Dagger', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1030, 'item_pocket_tower', 0, 0, 0, 0, 'Pocket Tower', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1032, 'item_pocket_roshan', 1000, 0, 0, 0, 'Pocket Roshan', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (287, 'item_keen_optic', 0, 0, 0, 0, 'Keen Optic', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (288, 'item_grove_bow', 0, 0, 0, 0, 'Grove Bow', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (289, 'item_quickening_charm', 0, 0, 0, 0, 'Quickening Charm', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (290, 'item_philosophers_stone', 0, 0, 0, 0, 'Philosopher''s Stone', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (291, 'item_force_boots', 0, 0, 0, 0, 'Force Boots', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (292, 'item_desolator_2', 0, 0, 0, 0, 'Stygian Desolator', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (293, 'item_phoenix_ash', 0, 0, 0, 0, 'Phoenix Ash', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (294, 'item_seer_stone', 0, 0, 0, 0, 'Seer Stone', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (295, 'item_greater_mango', 0, 0, 0, 0, 'Greater Mango', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (302, 'item_elixer', 0, 0, 0, 0, 'Elixir', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (297, 'item_vampire_fangs', 0, 0, 0, 0, 'Vampire Fangs', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (298, 'item_craggy_coat', 0, 0, 0, 0, 'Craggy Coat', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (84, 'item_flying_courier', 150, 0, 0, 0, 'Flying Courier', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (195, 'item_recipe_spirit_vessel', 600, 0, 0, 1, 'Recipe: Spirit Vessel', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1, 'item_blink', 2250, 0, 0, 0, 'Blink Dagger', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (600, 'item_overwhelming_blink', 6800, 0, 0, 0, 'Overwhelming Blink', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (603, 'item_swift_blink', 6800, 0, 0, 0, 'Swift Blink', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (604, 'item_arcane_blink', 6800, 0, 0, 0, 'Arcane Blink', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (606, 'item_recipe_arcane_blink', 1750, 0, 0, 1, 'Recipe: Arcane Blink', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (607, 'item_recipe_swift_blink', 1750, 0, 0, 1, 'Recipe: Swift Blink', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (608, 'item_recipe_overwhelming_blink', 1750, 0, 0, 1, 'Recipe: Overwhelming Blink', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (2, 'item_blades_of_attack', 450, 0, 0, 0, 'Blades of Attack', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (3, 'item_broadsword', 1000, 0, 0, 0, 'Broadsword', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (4, 'item_chainmail', 550, 0, 0, 0, 'Chainmail', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (5, 'item_claymore', 1350, 0, 0, 0, 'Claymore', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (6, 'item_helm_of_iron_will', 925, 0, 0, 0, 'Helm of Iron Will', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (7, 'item_javelin', 1100, 0, 0, 0, 'Javelin', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (8, 'item_mithril_hammer', 1600, 0, 0, 0, 'Mithril Hammer', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (162, 'item_sange', 2050, 0, 0, 0, 'Sange', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (28, 'item_sobi_mask', 175, 0, 0, 0, 'Sage''s Mask', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (29, 'item_boots', 500, 0, 0, 0, 'Boots of Speed', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (31, 'item_cloak', 500, 0, 0, 0, 'Cloak', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (32, 'item_talisman_of_evasion', 1300, 1, 0, 0, 'Talisman of Evasion', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (33, 'item_cheese', 1000, 0, 0, 0, 'Cheese', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (34, 'item_magic_stick', 200, 0, 0, 0, 'Magic Stick', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (35, 'item_recipe_magic_wand', 150, 0, 0, 1, 'Recipe: Magic Wand', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (223, 'item_meteor_hammer', 2350, 0, 0, 0, 'Meteor Hammer', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (366, 'item_apex', 0, 0, 0, 0, 'Apex', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (218, 'item_ward_dispenser', 50, 0, 0, 0, 'Observer and Sentry Wards', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (44, 'item_tango', 90, 0, 0, 0, 'Tango', null);
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (116, 'item_black_king_bar', 4050, 0, 0, 0, 'Black King Bar', 'Grants Spell Immunity. Duration decreases with each use.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (30, 'item_gem', 900, 0, 0, 0, 'Gem of True Sight', 'Grants the ability to see invisible units and wards to any allied vision within <strong>900</strong> range of its carrier.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (208, 'item_abyssal_blade', 6325, 0, 0, 0, 'Abyssal Blade', 'Stuns a target enemy unit for <strong>2</strong> seconds.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (119, 'item_shivas_guard', 4850, 0, 0, 0, 'Shiva''s Guard', 'Emits a freezing wave that deals <strong>200</strong> magical damage to enemies and slows their movement by <strong>40%</strong> for <strong>4</strong> seconds.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (229, 'item_solar_crest', 2625, 0, 0, 0, 'Solar Crest', 'When cast on an ally, grants them <strong>6</strong> armor, <strong>50</strong> attack speed, and <strong>10%</strong> movement speed. When cast on an enemy, removes <strong>6</strong> armor, <strong>50</strong>attack speed, and <strong>10%</strong> movement speed.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (210, 'item_heavens_halberd', 3550, 0, 0, 0, 'Heaven''s Halberd', 'Prevents a target from attacking for <strong>3</strong> seconds on melee targets, and <strong>5</strong> seconds on ranged targets.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (96, 'item_sheepstick', 5675, 0, 0, 0, 'Scythe of Vyse', 'Turns a target unit into a harmless critter for <strong>3.5</strong> seconds. The target has a base movement speed of <strong>140</strong> and will be silenced, muted, and disarmed.
Instantly destroys illusions.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (152, 'item_invis_sword', 3000, 0, 0, 0, 'Shadow Blade', 'Makes you invisible for <strong>14</strong> seconds, or until you attack or cast a spell. While Shadow Walk is active, you move <strong>20%</strong> faster and can move through units.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (98, 'item_orchid', 3475, 0, 0, 0, 'Orchid Malevolence', 'Silences the target unit for <strong>5</strong> seconds. At the end of the silence, <strong>30%</strong> of the damage received while silenced is inflicted as bonus magical damage.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (176, 'item_ethereal_blade', 4300, 0, 0, 0, 'Ethereal Blade', 'Converts the target unit to ethereal form, rendering them immune to physical damage, but unable to attack and <strong>40%</strong> more vulnerable to magic damage. Lasts for <strong>4</strong> seconds on allies and <strong>4</strong> seconds on enemies.

Enemy targets are also slowed by <strong>80%</strong>, and take <strong>1.5 x</strong> your primary attribute <strong> + 125</strong> as magical damage.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (256, 'item_aeon_disk', 3000, 0, 0, 0, 'Aeon Disk', 'When you take damage and your health falls below <strong>70%</strong>, a strong dispel is applied and you gain a <strong>2.5</strong> second buff that provides <strong>+ 75%</strong> Status Resistance and causes all damage you deal and are dealt to be reduced to zero. Only triggers on player based damage. Cooldown increases every time it triggers.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (145, 'item_bfury', 4130, 0, 0, 0, 'Battle Fury', 'Deals <strong>70%</strong> of attack damage as physical damage in a cone up to <strong>650</strong> around the target. Deals <strong>40%</strong>against creeps. (Melee Only)');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (135, 'item_monkey_king_bar', 4975, 0, 0, 0, 'Monkey King Bar', 'Grants each attack a <strong>80%</strong> chance to pierce through evasion and deal <strong>70</strong> bonus magical damage.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (692, 'item_eternal_shroud', 3300, 0, 0, 0, 'Eternal Shroud', 'Creates a spell shield that absorbs up to <strong>400</strong> magical damage, converting damage taken into mana. Lasts <strong>12</strong> seconds.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (131, 'item_hood_of_defiance', 1500, 0, 0, 0, 'Hood of Defiance', 'Creates a spell shield that absorbs up to <strong>325</strong> magical damage. Lasts <strong>12</strong> seconds.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (166, 'item_maelstrom', 2700, 0, 0, 0, 'Maelstrom', 'Grants a <strong>30%</strong> chance on attack to release a bolt of electricity that leaps between <strong>4</strong> targets within a <strong>650</strong> radius, dealing <strong>140</strong> magical damage to each. Lightning proc pierces evasion.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (225, 'item_nullifier', 4725, 0, 0, 0, 'Nullifier', 'Dispels the target and applies a debuff for <strong>5</strong> seconds. Continuously dispels the target. Anytime the target is attacked, it will be slowed by <strong>80%</strong> for <strong>0.5</strong> seconds.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (1466, 'item_gungir', 6150, 0, 0, 0, 'Gleipnir', 'Roots all enemies in a target <strong>450</strong> radius for <strong>2</strong> seconds and deals <strong>220</strong> damage.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (206, 'item_rod_of_atos', 2750, 0, 0, 0, 'Rod of Atos', 'Roots the target for <strong>2</strong> seconds.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (137, 'item_radiance', 5150, 0, 0, 0, 'Radiance', 'When active, scorches enemies for <strong>60</strong> magical damage per second, and causes them to miss <strong>17%</strong> of their attacks. Illusions deal <strong>35</strong> magical damage per second.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (143, 'item_basher', 2950, 0, 0, 0, 'Skull Basher', 'Grants melee heroes a <strong>25%</strong> chance on hit to stun the target for <strong>1.5</strong> seconds and deal <strong>100</strong> bonus physical damage. Bash chance for ranged heroes is <strong>10%</strong>.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (37, 'item_ghost', 1500, 0, 0, 0, 'Ghost Scepter', 'You enter ghost form for <strong>4</strong> seconds, becoming immune to physical damage, but are unable to attack and <strong>40%</strong> more vulnerable to magic damage.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (127, 'item_blade_mail', 2125, 0, 0, 0, 'Blade Mail', 'For 4.5 seconds, the damage returned from all sources is increased by <strong>80%</strong>.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (174, 'item_diffusal_blade', 3150, 0, 0, 0, 'Diffusal Blade', 'Each attack burns <strong>40</strong> mana from the target, and deals <strong>1</strong> physical damage per burned mana.

Burns <strong>12</strong> mana per attack from melee illusions and <strong>8</strong> mana per attack from ranged illusions.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (158, 'item_mjollnir', 5600, 0, 0, 0, 'Mjollnir', 'Places a charged shield on a target unit for <strong>15</strong> seconds which has a <strong>20%</strong> chance to release a <strong>225</strong> magical damage shocking bolt at a nearby attacker and <strong>4</strong> additional enemies.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (168, 'item_desolator', 3500, 0, 0, 0, 'Desolator', 'Your attacks reduce the target''s armor by <strong>5</strong> for <strong>7</strong> seconds.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (249, 'item_silver_edge', 5450, 0, 0, 0, 'Silver Edge', 'Makes you invisible for <strong>14</strong> seconds, or until you attack or cast a spell. While invisible, you move <strong>25%</strong> faster and can move through units.

Attacking to end the invisibility will deal <strong>175</strong> bonus physical damage and a guaranteed <strong>160%</strong> critical strike to the target, and disable their passive abilities for <strong>4</strong> seconds.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (250, 'item_bloodthorn', 6275, 0, 0, 0, 'Bloodthorn', 'Silences a target for <strong>5</strong> seconds. At the end of the silence, an additional <strong>30%</strong> of all damage taken during the silence will be dealt to the target as magical damage.

All attacks on the silenced target will have True Strike and <strong>100%</strong> chance to crit for <strong>130%</strong> damage.');
INSERT INTO public.items (id, name, cost, secret_shop, side_shop, recipe, localized_name, localized_description) VALUES (123, 'item_sphere', 4600, 0, 0, 0, 'Linken Sphere', 'Temporarily removes Spellblock from the item''s owner and transfers it to an allied unit for <strong>12</strong> seconds.');